import xml.etree.ElementTree as ET

ts_path = "translations/qgc_source_zh_CN.ts"

T = {
"  Multiple buttons that have the same action must be pressed simultaneously to invoke the action.": "  具有相同动作的多个按钮必须同时按下才能执行该动作。",
"  To change this configuration, select the desired frame class below and then reboot the vehicle.": "  要更改此配置，请在下方选择所需的机架类别，然后重启载具。",
"  seconds": "  秒",
"  seconds ...": "  秒...",
"  to a powered USB port on your computer, not through a USB hub. ": "  到电脑的带电 USB 端口，不要通过 USB 集线器。",
"  via USB to ": "  通过 USB 连接到 ",
"<br />Motors are currently assigned to a different output.\nBy saying yes, all motors will be reassigned to the first %1 channels of the selected output (%2).<br />": "<br />电机当前已分配到不同的输出。\n选择\"是\"后，所有电机将被重新分配到所选输出 (%2) 的前 %1 个通道。<br />",
"<br />No motors are assigned yet.\nBy saying yes, all motors will be assigned to the first %1 channels of the selected output (%2)\n (you can also first assign all motors, then start the identification).<br />": "<br />尚未分配电机。\n选择\"是\"后，所有电机将被分配到所选输出 (%2) 的前 %1 个通道\n（您也可以先分配所有电机，然后开始识别）。<br />",
"<br> Controls": "<br> 控制",
"AHRS": "AHRS",
"Action JSON files should be created in the '%1' folder.": "动作 JSON 文件需要放在\"%1\"目录下。",
"Active <br> Gimbal: ": "活动<br>云台：",
"Address in hex. Default is E7E7E7E7E7.": "十六进制地址。默认为 E7E7E7E7E7。",
"Adjust orientations as needed.\n\nROTATION_NONE indicates component points in direction of flight.": "根据需要调整方向。\n\nROTATION_NONE 表示组件指向飞行方向。",
"Airmode (disable during tuning) <b><a href=\"https://docs.px4.io/main/en/config_mc/pid_tuning_guide_multicopter.html#airmode-mixer-saturation\">?</a></b>": "Airmode（调参时禁用）<b><a href=\"https://docs.px4.io/main/en/config_mc/pid_tuning_guide_multicopter.html#airmode-mixer-saturation\">?</a></b>",
"Allow <br> takeover": "允许<br>接管",
"Allows access to additional providers": "允许访问额外的地图提供商",
"Also make sure you are only powered via USB ": "同时确保仅通过 USB 供电 ",
"Android: Don't save to SD card": "Android：不保存到 SD 卡",
"Are you sure you want to delete '%1' preset?": "确认删除\"%1\"预设？",
"Are you sure you want to delete '%1'?": "确认删除\"%1\"？",
"Are you sure you want to delete the selected log files?": "确认删除所选日志文件？",
"Are you sure you want to upload the selected log files?": "确认上传所选日志文件？",
"Area": "面积",
"Area: m²": "面积：平方米（m²）",
"Attempt to load new log while log being played": "尝试在日志回放时加载新日志",
"Autotune: Ack error %1": "自动调参：确认错误 %1",
"Autotune: Failed": "自动调参：失败",
"Autotune: In progress": "自动调参：进行中",
"Autotune: Not performed": "自动调参：未执行",
"Autotune: Success": "自动调参：成功",
"Autotune: Unknown error": "自动调参：未知错误",
"Autotune: in progress": "自动调参：进行中",
"Autotune: initializing": "自动调参：初始化中",
"Autotune: pitch": "自动调参：俯仰",
"Autotune: roll": "自动调参：横滚",
"Autotune: yaw": "自动调参：偏航",
"Broadcast%1": "广播%1",
"Change takeover condition:": "更改接管条件：",
"Change the equivalent airspeed setpoint.": "更改等效空速设定值。",
"Change the forward flight loiter radius.": "更改前飞盘旋半径。",
"Change the maximum horizontal cruise speed.": "更改最大水平巡航速度。",
"Click \"Refresh\" to authorize": "点击\"刷新\"以授权",
"Click Ok to place your CRSF receiver in the bind mode.": "点击确定将 CRSF 接收机置于对频模式。",
"Click Ok to place your Spektrum receiver in the bind mode.": "点击确定将 Spektrum 接收机置于对频模式。",
"Click Ok to start calibration.": "点击确定开始校准。",
"Click anywhere to hide": "点击任意位置隐藏",
"Click on the map to add vertices. Click 'Done Fencing' when finished.": "在地图上点击添加顶点。完成后点击\"完成围栏\"。",
"Clicking 'Apply' will save the changes you have made to your airframe configuration.<br><br>                                                                        All vehicle parameters other than Radio Calibration will be reset.<br><br>                                                                        Your vehicle will also be restarted in order to complete the process.": "点击\"应用\"将保存您对机体配置所做的更改。<br><br>                                                                        除遥控校准外的所有载具参数将被重置。<br><br>                                                                        载具也将重启以完成此过程。",
"Computed Font Height:": "计算得到的字体高度：",
"Computed Screen Height:": "计算得到的屏幕高度：",
"Computed Screen Width:": "计算得到的屏幕宽度：",
"Computer vision position": "计算机视觉位置",
"Configure some outputs in order to test them.": "配置一些输出以便测试。",
"Connection status: %1": "连接状态：%1",
"Controlled By vehicle": "由载具控制",
"Controlled by vehicle": "由载具端控制",
"Could Not Read Data - Link is Disconnected!": "无法读取数据 - 链路已断开！",
"Could Not Read Data - No Data Available!": "无法读取数据 - 无可用数据！",
"Could Not Send Data - Link is Disconnected!": "无法发送数据 - 链路已断开！",
"Could Not Send Data - Write Failed: %1": "无法发送数据 - 写入失败：%1",
"Could Not Send Data - Write Returned 0 Bytes": "无法发送数据 - 写入返回 0 字节",
"Could not open port: %1": "无法打开端口：%1",
"Current Base Position": "当前基准位置",
"Current alttiude": "当前高度",
"Current mission must be paused prior to uploading a new Plan": "上传新计划前必须暂停当前任务",
"Custom actions file - incorrect format: %1": "自定义动作文件 - 格式错误：%1",
"Custom actions file - incorrect format: JsonValue not an object": "自定义动作文件 - 格式错误：JsonValue 不是对象",
"Custom baud rate direction is unsupported": "不支持自定义波特率方向",
"DNSServiceProcessResult Error: %1": "DNS 服务处理结果错误：%1",
"Damping: increase to reduce overshoots and oscillations, but not higher than really needed.": "阻尼：增大可减少超调和振荡，但不要超过实际需要。",
"Delete %1 and all its tiles.\n\nIs this really what you want?": "删除 %1 及其所有地图块。\n\n您确定要这样做吗？",
"Delete log file after uploading": "上传后删除日志文件",
"Device disappeared from the system": "设备已从系统中消失",
"Device is already open": "设备已打开",
"Device is not open": "设备未打开",
"Differential Gain (FW_PR_D)": "微分增益 (FW_PR_D)",
"Differential Gain (FW_RR_D)": "微分增益 (FW_RR_D)",
"Differential Gain (MC_PITCHRATE_D)": "微分增益 (MC_PITCHRATE_D)",
"Differential Gain (MC_ROLLRATE_D)": "微分增益 (MC_ROLLRATE_D)",
"Differential gain (MPC_XY_VEL_D_ACC)": "微分增益 (MPC_XY_VEL_D_ACC)",
"Differential gain (MPC_Z_VEL_D_ACC)": "微分增益 (MPC_Z_VEL_D_ACC)",
"Differential pressure": "差压",
"Discard Unsaved Changes, Load New Plan From Vehicle": "放弃未保存的更改，从载具加载新计划",
"Downloading Imageries: ": "下载影像：",
"EMERGENCY HAS BEEN DECLARED, Press and Hold for 3 seconds to cancel": "已宣布紧急状态，按住 3 秒取消",
"ESC Calibration failed. ": "电调校准失败。",
"Edit position...": "编辑位置…",
"Emit heartbeat": "发送心跳包",
"Enable horizontal velocity slider (if enabled, individual velocity limit parameters are automatically set)": "启用水平速度滑块（启用后将自动设置各速度限制参数）",
"Enable responsiveness slider (if enabled, acceleration limit parameters and others are automatically set)": "启用响应性滑块（启用后将自动设置加速度限制等参数）",
"Enable vertical velocity slider (if enabled, individual velocity limit parameters are automatically set)": "启用垂直速度滑块（启用后将自动设置各速度限制参数）",
"Ensure distance from launch to transition direction is far enough to complete transition.": "确保起飞到转换方向的距离足够完成转换。",
"Error Registering Zeroconf: %1": "注册 Zeroconf 错误：%1",
"Error reading from device": "从设备读取错误",
"Error writing to device": "写入设备错误",
"Example: 127.0.0.1:14550": "示例：127.0.0.1:14550",
"FW(vtol)": "固定翼(VTOL)",
"Failed to Serialize Terrain Tile": "序列化地形图块失败",
"Failed to bind UDP socket to port": "无法绑定 UDP 端口",
"Failed to flush": "刷新失败",
"Failed to load custom actions file: `%1` error: `%2`": "加载自定义动作文件失败：`%1` 错误：`%2`",
"Failed to read polygon object.": "读取多边形对象失败。",
"Failed to read polyline object.": "读取折线对象失败。",
"Failed to set Break Enabled": "设置 Break 启用失败",
"Failed to set DTR": "设置 DTR 失败",
"Failed to set Flow Control": "设置流控失败",
"Failed to set RTS": "设置 RTS 失败",
"Failed to set StopBits": "设置停止位失败",
"Failed to set baud rate": "设置波特率失败",
"Failed to set data bits": "设置数据位失败",
"Failed to set parameters": "设置参数失败",
"Failed to set parity": "设置校验失败",
"Failed to start async read": "启动异步读取失败",
"Failed to stop async read": "停止异步读取失败",
"Failed to write data": "写入数据失败",
"Fast compass calibration given vehicle position and yaw. This ": "给定载具位置和偏航角的快速罗盘校准。这",
"Feedforward Gain (FW_PR_FF)": "前馈增益 (FW_PR_FF)",
"Feedforward Gain (FW_RR_FF)": "前馈增益 (FW_RR_FF)",
"Feedforward Gain (FW_YR_FF)": "前馈增益 (FW_YR_FF)",
"Feedforward gused to compensate for aerodynamic damping.": "前馈增益用于补偿气动阻尼。",
"Fence margin": "围栏余量",
"Fetch elevation data": "获取高程数据",
"File": "文件",
"File does not contain a polygon.": "文件不包含多边形。",
"File does not contain a polyline.": "文件不包含折线。",
"File is not a .shp file: %1": "文件不是 .shp 文件：%1",
"File not found: %1": "未找到文件：%1",
"File open failed: file:error %1 %2": "文件打开失败：文件错误 %1 %2",
"Final approach": "最终进近",
"Fixed Wing Landing Pattern: Setting the loiter and landing altitudes with different settings for altitude relative is no longer supported. Both have been set to relative altitude. Be sure to adjust/check your plan prior to flight.": "固定翼降落模式：不再支持为盘旋高度和降落高度设置不同的高度相对模式。两者均已设置为相对高度。飞行前请务必调整/检查您的计划。",
"Flight Behavior is used to configure flight characteristics.": "飞行行为用于配置飞行特性。",
"Follow Enabled": "已启用跟随",
"Follow System ID": "跟随系统 ID",
"Follow the forums actively when using it.": "使用时请积极关注论坛。",
"Font Point Size 10": "字号 10",
"Font Point Size 10.5": "字号 10.5",
"Font Point Size 11": "字号 11",
"Font Point Size 11.5": "字号 11.5",
"Font Point Size 12": "字号 12",
"Font Point Size 12.5": "字号 12.5",
"Font Point Size 13": "字号 13",
"Font Point Size 13.5": "字号 13.5",
"Font Point Size 14": "字号 14",
"Font Point Size 14.5": "字号 14.5",
"Font Point Size 15": "字号 15",
"Font Point Size 15.5": "字号 15.5",
"Font Point Size 16": "字号 16",
"Font Point Size 16.5": "字号 16.5",
"Font Point Size 17": "字号 17",
"Forgot Your Password?": "忘记密码？",
"Format Camera Storage": "格式化相机存储",
"Forwarding traffic: Mavlink traffic will keep being forwarded until application restarts": "转发流量：MAVLink 流量将持续转发直到应用重启",
"Forwards": "转发",
"Frame setup allows you to choose your vehicle's motor configuration. Install <b>clockwise</b><br>propellers on the <b>green thrusters</b> and <b>counter-clockwise</b> propellers on the <b>blue thrusters</b><br>(or vice-versa). The flight controller will need to be rebooted to apply changes.<br>When selecting a frame, you can choose to load the default parameter set for that frame configuration if available.": "机架设置允许您选择载具的电机配置。在<b>绿色推进器</b>上安装<b>顺时针</b><br>螺旋桨，在<b>蓝色推进器</b>上安装<b>逆时针</b>螺旋桨<br>（或反之）。需要重启飞控以应用更改。<br>选择机架时，如果可用，您可以选择加载该机架配置的默认参数集。",
"GCS ": "地面站 ",
"GCS GPS": "地面站 GPS",
"Generally does not need much adjustment, reduce this when seeing slow oscillations.": "通常不需要太多调整，出现缓慢振荡时减小此值。",
"Generic MAVLink": "通用 MAVLink",
"Generic micro air vehicle": "通用微型飞行器",
"Geotagging failed. Couldn't extract time from image: %1": "地理标记失败。无法从图片提取时间：%1",
"Geotagging failed. Couldn't open image: %1": "地理标记失败。无法打开图片：%1",
"Geotagging failed. Couldn't write to image: %1": "地理标记失败。无法写入图片：%1",
"Get Device: ": "获取设备：",
"Grab or Release the cargo": "抓取或释放货物",
"GroundStation Location": "地面站位置",
"Height rate feed forward (FW_T_HRATE_FF)": "高度速率前馈 (FW_T_HRATE_FF)",
"Horizontal (Y direction, sidewards)": "水平（Y 方向，侧向）",
"Horizontal velocity (m/s)": "水平速度 (m/s)",
"Host name": "主机名",
"Host name:": "主机名：",
"If Basic ID is already set on the RID device, this will be registered as Basic ID 2": "如果 RID 设备已设置基本 ID，此项将注册为基本 ID 2",
"If an emergency is declared, Emergency Text will be broadcast even if Broadcast setting is not enabled.": "如果宣布紧急状态，即使未启用广播设置，也将广播紧急文本。",
"If upgrade failed, make sure to connect ": "如果升级失败，请确保连接 ",
"Ignoring automatically in ": "自动忽略中 ",
"Images have already been tagged. Existing images will be removed.": "图片已被标记。现有图片将被删除。",
"Increase for more responsiveness, reduce if the attitude overshoots (there is only a setpoint when yaw is fixed, i.e. when centering the stick).": "增大可提高响应性，姿态超调时减小（仅在偏航固定时即摇杆居中时有设定值）。",
"Increase for more responsiveness, reduce if the attitude overshoots.": "增大可提高响应性，姿态超调时减小。",
"Increase for more responsiveness, reduce if the position overshoots (there is only a setpoint when hovering, i.e. when centering the stick).": "增大可提高响应性，位置超调时减小（仅在悬停时即摇杆居中时有设定值）。",
"Increase for more responsiveness, reduce if the velocity overshoots (and increasing D does not help).": "增大可提高响应性，速度超调时减小（增大 D 无效时）。",
"Increase to reduce steady-state error": "增大可减少稳态误差",
"Increase to reduce steady-state error (e.g. wind)": "增大可减少稳态误差（如风）",
"Increasing this leads to rounder turns in missions (corner cutting). Use the minimum value for accurate corner tracking.": "增大此值会导致任务中转弯更圆滑（切角）。使用最小值以准确跟踪拐角。",
"Increment Vehicle Id": "递增载具 ID",
"Integral Gain (FW_PR_I)": "积分增益 (FW_PR_I)",
"Integral Gain (FW_RR_I)": "积分增益 (FW_RR_I)",
"Integral Gain (FW_YR_D)": "积分增益 (FW_YR_D)",
"Integral Gain (FW_YR_I)": "积分增益 (FW_YR_I)",
"Integral Gain (MC_PITCHRATE_I)": "积分增益 (MC_PITCHRATE_I)",
"Integral Gain (MC_ROLLRATE_I)": "积分增益 (MC_ROLLRATE_I)",
"Integral Gain (MC_YAWRATE_I)": "积分增益 (MC_YAWRATE_I)",
"Integral gain (MPC_XY_VEL_I_ACC)": "积分增益 (MPC_XY_VEL_I_ACC)",
"Integral gain (MPC_Z_VEL_I_ACC)": "积分增益 (MPC_Z_VEL_I_ACC)",
"Internal Error: Parameter MetaData major must be 1": "内部错误：参数元数据主版本必须为 1",
"Internal error - MAV_COMP_ID_ALL not supported": "内部错误 - 不支持 MAV_COMP_ID_ALL",
"Internal error: Unable to find coordinates node in KML": "内部错误：无法在 KML 中找到坐标节点",
"Invalid Nak format": "无效 Nak 格式",
"Invalid baud rate value": "无效波特率值",
"Invalid data or size": "无效数据或大小",
"Invalid sockfd": "无效 sockfd",
"Json file: '%1'. %2": "JSON 文件：'%1'。%2",
"Keep Current Plan, Don't Update From Vehicle": "保留当前计划，不从载具更新",
"Kite": "风筝",
"Land Descent Rate:": "降落下降率：",
"Land and disarm the vehicle in order to apply the parameters.": "降落并上锁载具以应用参数。",
"Landing gear deploy": "起落架展开",
"Landing gear retract": "起落架收起",
"Laser based position": "激光定位",
"Lat: ": "纬度：",
"Lat: %1": "纬度：%1",
"Learning": "学习中",
"Limit the horizonal velocity (applies to all modes).": "限制水平速度（适用于所有模式）。",
"Limit the vertical velocity (applies to all modes).": "限制垂直速度（适用于所有模式）。",
"Link %1: %2": "链路 %1：%2",
"Link %1: (Device: %2) %3": "链路 %1：(设备：%2) %3",
"Link %1: (Host: %2 Port: %3) %4": "链路 %1：(主机：%2 端口：%3) %4",
"Link %1: (Port: %2) %3": "链路 %1：(端口：%2) %3",
"Link: %1, %2.": "链路：%1，%2。",
"List directory failed": "列出目录失败",
"Load from file for review...": "从文件加载以查看…",
"Log Replay Link Error": "日志回放链路错误",
"Log Replay Link Settings": "日志回放链路设置",
"Log files (*.txt)": "日志文件 (*.txt)",
"Logging categories": "日志类别",
"Loiter to QLand": "盘旋到快速降落",
"MAVLink 2 Signing": "MAVLink 2 签名",
"MAVLink 2.0 Log Record (PX4 only)": "MAVLink 2.0 日志记录（仅 PX4）",
"MAVLink 2.0 Log Upload (PX4 only)": "MAVLink 2.0 日志上传（仅 PX4）",
"MAVLink 2.0 Log Uploads (PX4 Pro Only)": "MAVLink 2.0 日志上传（仅 PX4 Pro）",
"MAVLink 2.0 Logging (PX4 Pro Only)": "MAVLink 2.0 日志记录（仅 PX4 Pro）",
"MAVLink Actions": "MAVLink 动作",
"MAVLink Forwarding": "MAVLink 转发",
"MAVLink Logging": "MAVLink 日志",
"MAVLink System ID": "MAVLink 系统 ID",
"MR(vtol)": "多旋翼(VTOL)",
"Mag %1 Orientation": "磁力计 %1 朝向",
"Make sure you remove all props.": "确保已拆除所有螺旋桨。",
"Make the specified location the estimator origin.": "将指定位置设为估计器原点。",
"Make this log public": "允许公开该日志",
"Make this log publicly available": "允许公开该日志",
"Mannual": "手动",
"Manual Magnetic Declination": "手动磁偏角",
"Map type:": "地图类型：",
"Mavlink camera stream is automatically configured": "MAVLink 相机视频流已自动配置",
"Mavlink traffic is being forwarded to a support server": "MAVLink 流量正转发到支持服务器",
"MavlinkActions": "MAVLink 动作",
"Military Grid Reference": "军用网格参考",
"Mixed Modes": "混合模式",
"More than one entity found.": "找到多个实体。",
"Motor Interlock disable": "电机互锁禁用",
"Motor Interlock enable": "电机互锁启用",
"Motor Order Identification and Assignment": "电机顺序识别和分配",
"Motors reversed": "电机反转",
"Move '%1' %2 to the %3 location. %4": "将\"%1\" %2 移动到 %3 位置。%4",
"Multiplier for P, I and D gains: increase for more responsiveness, reduce if the rates overshoot (and increasing D does not help).": "P、I、D 增益的倍数：增大可提高响应性，速率超调时减小（增大 D 无效时）。",
"NMEA External GPS Device": "NMEA 外置 GPS 设备",
"NMEA GPS": "NMEA GPS",
"NMEA GPS Baudrate": "NMEA GPS 波特率",
"NMEA stream UDP port": "NMEA 数据流 UDP 端口",
"Name:": "名称：",
"Navigator w/ Blue Robotics Power Sense Module": "Navigator 带 Blue Robotics 电源检测模块",
"No firmware was found for the current selection.": "当前选择无可用固件。",
"No response to operator control request": "操作员控制请求无响应",
"No supported type found in KML file.": "KML 文件中未找到支持的类型。",
"No supported types found.": "未找到支持的类型。",
"No, set frame only": "否，仅设置机架",
"Normal helicopter with tail rotor.": "带尾桨的普通直升机。",
"Not Supported(Over APM 4.1)": "不支持（APM 4.1 以上）",
"Not all motors are assigned yet. Either clear all existing assignments or assign all motors to an output.": "并非所有电机都已分配。请清除所有现有分配或将所有电机分配到输出。",
"Not connecting to a bootloader": "未连接到引导加载程序",
"Note: Distance/area/temperature are fixed to metric units; speed supports only m/s and km/h.": "说明：距离/面积/温度为固定公制单位；速度仅支持 m/s 与 km/h。",
"Note: For best perfomance, please disable AutoConnect to UDP devices on the General page.": "注意：为获得最佳性能，请在通用页面禁用 UDP 设备自动连接。",
"OPERATOR ID": "操作员 ID",
"Offset Type": "偏移类型",
"Offset X": "偏移 X",
"Offset Y": "偏移 Y",
"Offset Z": "偏移 Z",
"On this menu you can forward mavlink telemetry to an ardupilot support engineer.": "在此菜单中您可以将 MAVLink 遥测转发给 ArduPilot 支持工程师。",
"Onboard ADSB peripheral": "机载 ADSB 外设",
"Onboard companion controller": "机载伴随控制器",
"Onboard gimbal": "机载云台",
"One or more actuator still needs to be assigned to an output.": "一个或多个执行器仍需分配到输出。",
"Only WGS84 or UTM projections are supported.": "仅支持 WGS84 或 UTM 投影。",
"Only single part polygons are supported.": "仅支持单部分多边形。",
"Only single part polylines are supported.": "仅支持单部分折线。",
"Open console log output file failed %1 : %2": "打开控制台日志输出文件失败 %1：%2",
"Operation timed out": "操作超时",
"Operator control unit / ground control station": "操作员控制单元/地面控制站",
"Optical Flow Camera": "光流相机",
"Orbit at location": "在位置处环绕",
"Ounces": "盎司",
"Overall Multiplier (MC_PITCHRATE_K)": "总倍数 (MC_PITCHRATE_K)",
"Overall Multiplier (MC_ROLLRATE_K)": "总倍数 (MC_ROLLRATE_K)",
"Overall Multiplier (MC_YAWRATE_K)": "总倍数 (MC_YAWRATE_K)",
"PRJ file open failed: %1": "PRJ 文件打开失败：%1",
"PX4 Vehicle": "PX4 载具",
"Pause selected vehicles at their current position.": "在当前位置暂停选中的载具。",
"Pitch axis rate controller D gain": "俯仰轴速率控制器 D 增益",
"Pitch axis rate controller I gain": "俯仰轴速率控制器 I 增益",
"Pitch axis rate controller P gain": "俯仰轴速率控制器 P 增益",
"Plan Flight": "规划飞行",
"Plan View - Vehicle Changed": "计划视图 - 载具已切换",
"Plan view - Vehicle Disconnected": "计划视图 - 载具已断开",
"Plan overwrite": "计划覆盖",
"Please enter an email address before uploading MAVLink log files.": "上传 MAVLink 日志文件前请先填写邮箱地址。",
"Please unplug your Pixhawk and/or Radio from USB.": "请拔出 Pixhawk 和/或电台的 USB 连接。",
"Plug in your device": "插入设备",
"Point <br> Home": "指向<br>起飞点",
"Porportional Gain (FW_PR_P)": "比例增益 (FW_PR_P)",
"Porportional Gain (FW_YR_P)": "比例增益 (FW_YR_P)",
"Porportional Gain.": "比例增益。",
"Porportional gain (FW_RR_P)": "比例增益 (FW_RR_P)",
"Porportional gain.": "比例增益。",
"Port is not Connected": "端口未连接",
"Port is not Writable": "端口不可写",
"Position Controller": "位置控制器",
"Position control mode (set this to 'simple' during tuning):": "位置控制模式（调参时设为\"简单\"）：",
"Power module not set up": "电源模块未设置",
"Preset name cannot be blank.": "预设名称不能为空。",
"Preset name cannot include the \"/\" character.": "预设名称不能包含\"/\"字符。",
"Press and Hold below button to declare emergency": "按住下方按钮宣布紧急状态",
"Propellers are removed - Enable slider and motors": "螺旋桨已拆除 - 启用滑块和电机",
"Propellers are removed - Enable sliders": "螺旋桨已拆除 - 启用滑块",
"Proportional Gain (MC_PITCH_P)": "比例增益 (MC_PITCH_P)",
"Proportional Gain (MC_ROLL_P)": "比例增益 (MC_ROLL_P)",
"Proportional Gain (MC_YAW_P)": "比例增益 (MC_YAW_P)",
"Proportional gain (MPC_XY_P)": "比例增益 (MPC_XY_P)",
"Proportional gain (MPC_XY_VEL_P_ACC)": "比例增益 (MPC_XY_VEL_P_ACC)",
"Proportional gain (MPC_Z_P)": "比例增益 (MPC_Z_P)",
"Proportional gain (MPC_Z_VEL_P_ACC)": "比例增益 (MPC_Z_VEL_P_ACC)",
"Provide Information": "提供信息",
"QGC functions do not support shift actions": "QGC 功能不支持移位动作",
"QML Desktop Available Area: ": "QML 桌面可用区域：",
"QML Pixel Density:": "QML 像素密度：",
"QML Pixel Density: ": "QML 像素密度：",
"QML Pixel Ratio:": "QML 像素比例：",
"QML Pixel Ratio: ": "QML 像素比例：",
"QML Screen Desktop:": "QML 屏幕桌面：",
"QML Screen Size:": "QML 屏幕尺寸：",
"QML Screen Size: ": "QML 屏幕尺寸：",
"Quad-rotor VTOL using a V-shaped quad config in vertical operation. Tailsitter": "垂直飞行时使用 V 形四旋翼配置的四旋翼 VTOL。尾座式",
"QuadPlane Acro": "QuadPlane 特技",
"QuadPlane AutoTune": "QuadPlane 自动调参",
"QuadPlane Hover": "QuadPlane 悬停",
"QuadPlane Land": "QuadPlane 降落",
"QuadPlane Loiter": "QuadPlane 盘旋",
"QuadPlane RTL": "QuadPlane 返航",
"QuadPlane Stabilize": "QuadPlane 自稳",
"Quadrotor": "四旋翼",
"RC receiver": "RC 接收机",
"RID COMMS": "RID 通信",
"ROTATION_NONE indicates component points in direction of flight.": "ROTATION_NONE 表示组件指向飞行方向。",
"RTK Streaming": "RTK 数据流",
"Radio Not Ready": "电台未就绪",
"Radio did not respond to ATI2 command": "电台未响应 ATI2 命令",
"Radio did not respond to command mode": "电台未响应命令模式",
"Radio did not return board id": "电台未返回板卡 ID",
"Rate Controller": "速率控制器",
"Reboot vehicle for changes to take effect.": "重启载具以使更改生效。",
"Rebooting board": "重启板卡中",
"Register Flight Plan": "注册飞行计划",
"Release <br> Control": "释放<br>控制",
"Remote Support": "远程支持",
"RemoteID Status": "远程 ID 状态",
"Remove Flight Plan": "移除飞行计划",
"Request Timeout (sec):": "请求超时（秒）：",
"Request sent: ": "请求已发送：",
"Require Confirmation for Go To Location in Guided Mode": "引导模式下前往位置需要确认",
"Reset Camera Defaults": "重置相机默认值",
"Reset Camera to Factory Settings": "恢复相机出厂设置",
"Reset To Default": "恢复默认",
"Reset failed": "重置失败",
"Reset successful": "重置成功",
"Responsiveness": "响应性",
"Restart application for changes to take effect.": "重启应用以使更改生效。",
"Restore Defaults": "恢复默认",
"Restore to Defaults": "恢复默认",
"Resume Download": "继续下载",
"Retract": "收起",
"Retracted": "已收起",
"Return At": "返航高度",
"Reverting back to takeover not allowed if GCS ": "如果地面站未在超时内接管，将恢复为不允许接管 ",
"Rightwards": "向右",
"Roll axis angle controller P gain": "横滚轴角度控制器 P 增益",
"Roll axis rate controller D gain": "横滚轴速率控制器 D 增益",
"Roll axis rate controller I gain": "横滚轴速率控制器 I 增益",
"Roll axis rate controller P gain": "横滚轴速率控制器 P 增益",
"Roll control to yaw feedforward (FW_RLL_TO_YAW_FF)": "横滚控制到偏航前馈 (FW_RLL_TO_YAW_FF)",
"Root of json file is not object: %1": "JSON 文件根不是对象：%1",
"Rotate Entry Point": "旋转入口点",
"Rover-Boat": "漫游车-船",
"SHPOpen failed.": "SHP 打开失败。",
"Satellite Communication": "卫星通信",
"Save CSV log of telemetry data": "保存遥测数据 CSV 日志",
"Save Settings As New Preset": "将设置另存为新预设",
"Save application data to SD Card": "将应用数据保存到 SD 卡",
"Save logs even if vehicle was not armed": "即使载具未解锁也保存日志",
"Save the current settings as a named preset.": "将当前设置保存为命名预设。",
"Save to SD card specified for application data. But SD card is write protected. Using internal storage.": "保存到为应用数据指定的 SD 卡。但 SD 卡被写保护。使用内部存储。",
"Save to SD card specified for application data. But no SD card present. Using internal storage.": "保存到为应用数据指定的 SD 卡。但无 SD 卡。使用内部存储。",
"Select <br> Gimbal": "选择<br>云台",
"Select Altitude Mode": "选择高度模式",
"Select Link to Connect": "选择要连接的链路",
"Select Mission Command": "选择任务指令",
"Select Polyline File": "选择折线文件",
"Select Reset to reset all parameters to their defaults.\n\nNote that this will also completely reset everything, including UAVCAN nodes, all vehicle settings, setup and calibrations.": "选择重置将所有参数恢复为默认值。\n\n注意这将完全重置一切，包括 UAVCAN 节点、所有载具设置、安装和校准。",
"Select Tuning:": "选择调参：",
"Select log save file": "选择日志保存文件",
"Select the specific receiver type below:": "在下方选择具体的接收机类型：",
"Selected: ": "已选：",
"Send Control Request:": "发送控制请求：",
"Send Status Text and Voice": "发送状态文本和语音",
"Send To Vehicle": "发送到载具",
"Send status text + voice": "发送状态文本 + 语音",
"Serial <none available>": "串口 <无可用>",
"Serial Link Error": "串口链路错误",
"Server Addresses (optional)": "服务器地址（可选）",
"Server name:": "服务器名称：",
"Set Estimator origin": "设置估计器原点",
"Set Home failed, terrain data not available for selected coordinate": "设置起飞点失败，所选坐标无地形数据",
"Set Logging": "设置日志",
"Set Rate:": "设置速率：",
"Set Spin Direction 1": "设置旋转方向 1",
"Set Spin Direction 2": "设置旋转方向 2",
"Set home here": "在此设置起飞点",
"Set the vehicle flight mode to %1": "将载具飞行模式设置为 %1",
"Set the vehicle heading towards the specified location.": "将载具航向设置为指向指定位置。",
"Set vehicle home as the specified location. This will affect Return to Home position": "将载具起飞点设为指定位置。这将影响返航位置",
"Show Acquire/Release control button": "显示获取/释放控制按钮",
"Show Latest": "显示最新",
"Show all settings (advanced)": "显示所有设置（高级）",
"Show gimbal Azimuth indicator in map": "在地图上显示云台方位角指示",
"Show obstacle distance overlay": "显示障碍物距离覆盖层",
"Show simple camera controls (DIGICAM_CONTROL)": "显示简易相机控制（DIGICAM_CONTROL）",
"Show zoom previews": "显示缩放预览",
"Signing Failure": "签名失败",
"Signing key has changed. Don't forget to send to Vehicle(s) if needed.": "签名密钥已变更。如需要请记得发送到载具。",
"Signing key has changed. Remember to send it to the vehicle for it to take effect.": "签名密钥已变更。如需生效，请记得发送到载具。",
"Signing keys should only be sent to the vehicle over secure links.": "签名密钥应仅通过安全链路发送到载具。",
"Signing signature mismatch": "签名不匹配",
"Simple accelerometer calibration is less precise but allows calibrating without rotating the vehicle. Check this if you have a large/heavy vehicle.": "简单加速度计校准精度较低，但无需旋转载具即可校准。如果您的载具较大/较重请勾选此项。",
"Slide or hold spacebar": "滑动或按住空格键",
"Socket is not Writable": "Socket 不可写",
"Socket is not connected": "Socket 未连接",
"Some Modes Hidden": "部分模式已隐藏",
"Specified altitude": "指定高度",
"Specified altitudes are Above Mean Sea Level.": "指定高度为海拔高度。",
"Specified altitudes are distance above terrain. Actual altitudes sent to vehicle are calculated from terrain data and sent as AMSL values.": "指定高度为离地高度。实际发送给载具的高度由地形数据计算并以 AMSL 值发送。",
"Specified altitudes are distance above terrain. The actual altitude flown is controlled by the vehicle either from terrain height maps being sent to vehicle or a distance sensor.": "指定高度为离地高度。实际飞行高度由载具通过地形高度图或距离传感器控制。",
"Specified altitudes are relative to launch position height.": "指定高度相对于起飞点高度。",
"Specify position": "指定位置",
"Spin Motor Again": "再次旋转电机",
"SquareFeet": "平方英尺",
"SquareKilometers": "平方千米",
"SquareMeters": "平方米",
"SquareMiles": "平方英里",
"Start AutoTune": "开始自动调参",
"Start Logging": "开始记录",
"Start Mock: ArduPilot Fixed Wing (ArduPlane)": "启动模拟：ArduPilot 固定翼（ArduPlane）",
"Start Mock: ArduPilot Multirotor (ArduCopter)": "启动模拟：ArduPilot 多旋翼（ArduCopter）",
"Start Mock: Generic Vehicle": "启动模拟：通用载具",
"Start Mock: Ground/General (ArduRover)": "启动模拟：地面/通用平台（ArduRover）",
"Start Mock: PX4 Vehicle": "启动模拟：PX4 载具",
"Start Mock: Sub/Boat (ArduSub)": "启动模拟：水下/船用（ArduSub）",
"Station Mode": "站点模式",
"Stop Logging": "停止记录",
"Stop One MockLink": "停止一个模拟链接",
"Stop one mock link": "停止一个模拟连接",
"Stream Rates (ArduPilot Only)": "数据流频率（仅 ArduPilot）",
"Support for Fly View custom actions has changed. The location of the files has changed. You will need to setup up your settings again from Fly View Settings.": "飞行视图自定义动作的支持已变更。文件位置已更改。您需要从飞行视图设置中重新设置。",
"Support for Joystick custom actions has changed. The format and location of the files has changed. New setting is available from Fly View Settings. File format is documented in user guide. Delete the %1 file to disable this warning": "摇杆自定义动作的支持已变更。文件格式和位置已更改。新设置可在飞行视图设置中找到。文件格式见用户指南。删除 %1 文件可禁用此警告",
"Surface vessel, boat, ship": "水面艇、船、舰",
"Surftrak": "地面追踪",
"Survey-in Active": "测量定位中",
"System %1": "系统 %1",
"System Wide Tile Cache": "系统级图块缓存",
"T": "温度",
"TCP Link Error": "TCP 链路错误",
"TCP URL": "TCP 地址",
"TCP-MPEG2 Video Stream": "TCP-MPEG2 视频流",
"Takeoff from ground and start the current mission for selected vehicles.": "从地面起飞并为选中的载具开始当前任务。",
"Takeover NOT allowed": "不允许接管",
"Takeover allowed": "允许接管",
"Telemetry Display": "遥测显示",
"Telemetry Logs (*.%1)": "遥测日志 (*.%1)",
"Terrain Frame": "地形坐标系",
"The Offline Map Cache database has been upgraded. Your old map cache sets have been reset.": "离线地图缓存数据库已升级。您的旧地图缓存集已重置。",
"The altitude mode can differ for each individual item.": "高度模式可以逐项不同。",
"The following parameters from the loaded file differ from what is currently set on the Vehicle. Click 'Ok' to update them on the Vehicle.": "加载文件中的以下参数与载具当前设置不同。点击\"确定\"在载具上更新它们。",
"The following speed values are used to calculate total mission time. They do not affect the flight speed for the mission.": "以下速度值用于计算总任务时间。它们不影响任务的飞行速度。",
"The latency between a pitch step input and the achieved setpoint (inverse to a P gain)": "俯仰阶跃输入与达到设定值之间的延迟（与 P 增益成反比）",
"The latency between a roll step input and the achieved setpoint (inverse to a P gain)": "横滚阶跃输入与达到设定值之间的延迟（与 P 增益成反比）",
"The log file '%1' is corrupt or empty.": "日志文件\"%1\"已损坏或为空。",
"The plan being worked on in the Plan View is not from the current vehicle. What would you like to do with that plan?": "计划视图中正在编辑的计划不来自当前载具。您想如何处理该计划？",
"The signing key should only be sent to the vehicle over a secure link.": "签名密钥应仅通过安全链路发送到载具。",
"The vehicle associated with the plan in the Plan View is no longer available. What would you like to do with that plan?": "计划视图中计划关联的载具已不可用。您想如何处理该计划？",
"There are no differences between the file loaded and the current settings on the Vehicle.": "加载的文件与载具当前设置之间没有差异。",
"There are still active connections to vehicles. Are you sure you want to exit?": "仍有到载具的活动连接。确定要退出吗？",
"There is a newer version of %1 available. You can download it from %2.": "有新版本的 %1 可用。您可以从 %2 下载。",
"Thermal": "热成像",
"Thermal View Mode": "热成像视图模式",
"This GCS": "本地面站",
"This GCS Mavlink System ID: ": "本地面站 MAVLink 系统 ID：",
"This Plan was created for a different firmware or vehicle type than the firmware/vehicle type of vehicle you are uploading to. This can lead to errors or incorrect behavior. It is recommended to recreate the Plan for the correct firmware/vehicle type.\n\nClick 'Ok' to upload the Plan anyway.": "此计划是为不同的固件或载具类型创建的，与您要上传到的固件/载具类型不同。这可能导致错误或不正确的行为。建议为正确的固件/载具类型重新创建计划。\n\n点击\"确定\"仍然上传计划。",
"This will automatically spin individual motors at 15% thrust.<br /><br />\n<b>Warning: Only proceed if you removed all propellers</b>.<br />\n%1\n<br />\nThe procedure is as following:<br />\n- After confirming, the first motor starts to spin for 0.5 seconds.<br />\n- Then click on the motor that was spinning.<br />\n- The above steps are repeated for all motors.<br />\n- The motor output functions will automatically be reassigned by the selected order.<br />\n<br />\nDo you wish to proceed?": "这将自动以 15% 推力旋转各个电机。<br /><br />\n<b>警告：仅在已拆除所有螺旋桨后继续</b>。<br />\n%1\n<br />\n步骤如下：<br />\n- 确认后，第一个电机开始旋转 0.5 秒。<br />\n- 然后点击正在旋转的电机。<br />\n- 对所有电机重复上述步骤。<br />\n- 电机输出功能将按所选顺序自动重新分配。<br />\n<br />\n是否继续？",
"This will delete all tiles INCLUDING the tile sets you have created yourself.\n\nIs this really what you want?": "这将删除所有图块，包括您自己创建的图块集。\n\n您确定要这样做吗？",
"Throttle": "油门",
"Tile Cache": "地图块缓存",
"Tile Count:": "图块数：",
"Tile Sets (*.%1)": "地图块集 (*.%1)",
"Tilt 90": "倾斜 90",
"Tiltrotor VTOL": "倾转旋翼 VTOL",
"Time Constant (FW_P_TC)": "时间常数 (FW_P_TC)",
"Time constant (FW_R_TC)": "时间常数 (FW_R_TC)",
"Time lapse capture not supported by this camera": "此相机不支持延时拍摄",
"Timeout while waiting for bytes written": "等待写入字节超时",
"Timeout while waiting for ready read": "等待就绪读取超时",
"Timeout:": "超时：",
"To level the horizon you need to place the vehicle in its level flight position and leave still.": "要调平地平线，需要将载具放在水平飞行位置并保持静止。",
"Too many tiles": "图块过多",
"Total message loss": "总丢包数",
"Total messages received": "已接收消息总数",
"Total messages sent (computed)": "已发送消息总数（计算值）",
"Touch Area display toggled": "触摸区域显示已切换",
"Trigger Dist": "触发距离",
"Tuning Setup is used to tune the flight controllers.": "调参设置用于调整飞控参数。",
"Turn off Advanced Mode?": "关闭高级模式？",
"Two-rotor VTOL using control surfaces in vertical operation in addition. Tailsitter": "垂直飞行时额外使用控制面的双旋翼 VTOL。尾座式",
"UDP h.264 Video Stream": "UDP h.264 视频流",
"UDP h.265 Video Stream": "UDP h.265 视频流",
"URL with {x} {y} {z} or {zoom} substitutions": "带 {x} {y} {z} 或 {zoom} 替换的 URL",
"UTM Service Editor": "UTM 服务编辑器",
"UTM projection is not in supported format. Must be PROJCS[\"WGS_1984_UTM_Zone_##N/S": "UTM 投影格式不支持。必须为 PROJCS[\"WGS_1984_UTM_Zone_##N/S",
"UTM-Adapter": "UTM 适配器",
"Unable to find LineString node in KML": "无法在 KML 中找到 LineString 节点",
"Unable to find Polygon node in KML": "无法在 KML 中找到 Polygon 节点",
"Unable to open file: %1 error: $%2": "无法打开文件：%1 错误：$%2",
"Unable to open file: '%1', error: %2": "无法打开文件：'%1'，错误：%2",
"Unable to open log file: '%1', error: %2": "无法打开日志文件：'%1'，错误：%2",
"Unable to parse KML file: %1 error: %2 line: %3": "无法解析 KML 文件：%1 错误：%2 行：%3",
"Unable to parse json file: %1 error: %2 offset: %3": "无法解析 JSON 文件：%1 错误：%2 偏移：%3",
"Unable to put radio into command mode +++": "无法将电台置于命令模式 +++",
"Unable to reboot radio (ready read)": "无法重启电台（就绪读取）",
"Unable to reopen log file %1: %2": "无法重新打开日志文件 %1：%2",
"Unable to save telemetry log. Application save directory is not set.": "无法保存遥测日志。应用保存目录未设置。",
"Unable to save telemetry log. Telemetry save directory \"%1\" does not exist.": "无法保存遥测日志。遥测保存目录\"%1\"不存在。",
"Unable to seek to new position": "无法定位到新位置",
"Unable to send command: %1.": "无法发送命令：%1。",
"Unable to start takeoff: Vehicle failed to arm.": "无法起飞：载具解锁失败。",
"Unable to start takeoff: Vehicle failed to change to Takeoff mode.": "无法起飞：载具未能切换到起飞模式。",
"Unable to start takeoff: Vehicle is already in the air.": "无法起飞：载具已在空中。",
"Unable to start takeoff: Vehicle not changing to %1 flight mode.": "无法起飞：载具未切换到 %1 飞行模式。",
"Unable to start takeoff: Vehicle rejected arming.": "无法起飞：载具拒绝解锁。",
"Unabled to find writable download location. Tried downloads and temp directory.": "无法找到可写的下载位置。已尝试下载和临时目录。",
"Unexpected Error": "意外错误",
"Unique:": "唯一：",
"Universal Transverse Mercator": "通用横轴墨卡托投影",
"Unsupported file type. Only .%1 and .%2 are supported.": "不支持的文件类型。仅支持 .%1 和 .%2。",
"Unsupported open mode": "不支持的打开模式",
"Upload Selected Log Files": "上传所选日志文件",
"Upwards": "向上",
"Use Azimuth instead of local yaw on top toolbar indicator": "工具栏指示器使用方位角而非本地偏航",
"Use GCS position instead": "改用地面站位置",
"Use MAV_CMD_CONDITION_GATE for pattern generation": "航线/图案生成时使用 MAV_CMD_CONDITION_GATE",
"Use current map position instead": "改用当前地图位置",
"Use loiter to altitude": "用盘旋到高度",
"Use manual tuning": "使用手动调参",
"Used to counteract the adverse yaw effect for fixed wings.": "用于抵消固定翼的不利偏航效应。",
"User ID": "用户 ID",
"VTOL Fixedrotor": "VTOL 固定旋翼",
"VTOL Tiltwing": "VTOL 倾转翼",
"VTOL reserved 5": "VTOL 保留 5",
"VWorld": "VWorld",
"Value Editor": "值编辑器",
"Value range": "值范围",
"Value: ": "值：",
"Valuec requires a connected vehicle for setup.": "Valuec 需要连接载具才能设置。",
"Vehicle %1 ": "载具 %1 ",
"Vehicle Action": "载具动作",
"Vehicle Error": "载具错误",
"Vehicle GPS Status": "载具 GPS 状态",
"Vehicle does not support guided rotate": "载具不支持引导旋转",
"Vehicle has no Valid positon, please provide it": "载具无有效位置，请提供",
"Vehicle reboot failed.": "载具重启失败。",
"Vehicle reboot required after change": "更改后需要重启载具",
"Velocity Controller": "速度控制器",
"Vertical velocity (m/s)": "垂直速度 (m/s)",
"Video Grid Lines": "视频网格线",
"Video Screen Fit": "视频屏幕适配",
"Video Stream Disabled": "视频流已禁用",
"Video decode priority": "视频解码优先级",
"WARNING!        \n\nThe auto-tuning procedure should be executed with caution and requires the vehicle to fly stable enough before attempting the procedure!         \n\nBefore starting the auto-tuning process, make sure that:         \n1. You have read the auto-tuning guide and have followed the preliminary steps         \n2. The current control gains are good enough to stabilize the drone in presence of medium disturbances         \n3. You are ready to abort the auto-tuning sequence by moving the RC sticks, if anything unexpected happens.         \n\nClick Ok to start the auto-tuning process.\n": "警告！\n\n自动调参程序应谨慎执行，且在尝试前需要载具能够稳定飞行！\n\n开始自动调参前，请确保：\n1. 您已阅读自动调参指南并完成了预备步骤\n2. 当前控制增益足以在中等扰动下稳定无人机\n3. 如果发生意外，您已准备好通过移动遥控摇杆来中止自动调参序列。\n\n点击确定开始自动调参过程。\n",
"WARNING: Photo interval is below minimum interval (%1 secs) supported by camera.": "警告：拍照间隔低于相机支持的最小间隔（%1 秒）。",
"WARNING: This will force arming of the vehicle bypassing any safety checks.": "警告：这将强制解锁载具，绕过所有安全检查。",
"Waiting for previous operator control request": "等待上一个操作员控制请求",
"Waiting on previous response to same command.": "等待同一命令的上一个响应。",
"Warning: a high responsiveness requires a vehicle with large thrust-to-weight ratio. The vehicle might lose altitude otherwise.": "警告：高响应性需要载具具有大推重比。否则载具可能掉高度。",
"Would you like to load the default parameters for the frame?": "是否加载该机架的默认参数？",
"Would you like to set the desired frame?": "是否设置所需的机架？",
"X (%1)": "X (%1)",
"X/Y position control": "X/Y 位置控制",
"Y (%1)": "Y (%1)",
"Yaw <br> Follow": "偏航<br>跟随",
"Yaw <br> Lock": "偏航<br>锁定",
"Yaw Behavior": "偏航行为",
"Yaw axis rate controller I gain": "偏航轴速率控制器 I 增益",
"Yaw axis rate controller P gain": "偏航轴速率控制器 P 增益",
"Yaw follow": "偏航跟随",
"Yaw locked": "偏航锁定",
"Yaw position": "偏航位置",
"Yes, Load default parameter set for %1": "是，加载 %1 的默认参数集",
"You are running %1 as root. You should not do this since it will cause other issues with %1.%1 will now exit.<br/><br/>": "您正在以 root 身份运行 %1。不应这样做，因为这会导致 %1 的其他问题。%1 现在将退出。<br/><br/>",
"You have a mission edit in progress which has not been saved/sent. If you close you will lose changes. Are you sure you want to close?": "您有一个正在编辑的任务尚未保存/发送。如果关闭将丢失更改。确定要关闭吗？",
"You have pending parameter updates to a vehicle. If you close you will lose changes. Are you sure you want to close?": "您有待处理的载具参数更新。如果关闭将丢失更改。确定要关闭吗？",
"You must choose a board type.": "必须选择板卡类型。",
"You must close all connections prior to replaying a log.": "回放日志前必须关闭所有连接。",
"You must select at least one log file to download.": "必须至少选择一个日志文件来下载。",
"Yuneec Mantis G": "Yuneec Mantis G",
"Z (%1)": "Z (%1)",
"Z/altitude control": "Z/高度控制",
"Zero Trims": "微调归零",
"Zero-Conf": "Zero-Conf",
"Zeroconf Register Error: %1": "Zeroconf 注册错误：%1",
"_activeVehicle(%1) _vehicleArmed(%2) guidedModeSupported(%3) _vehicleFlying(%4) _vehicleWasFlying(%5) _vehicleInRTLMode(%6) pauseVehicleSupported(%7) _vehiclePaused(%8) _flightMode(%9) _missionItemCount(%10) roiSupported(%11) orbitSupported(%12) _missionActive(%13) _hideROI(%14) _hideOrbit(%15)": "_activeVehicle(%1) _vehicleArmed(%2) guidedModeSupported(%3) _vehicleFlying(%4) _vehicleWasFlying(%5) _vehicleInRTLMode(%6) pauseVehicleSupported(%7) _vehiclePaused(%8) _flightMode(%9) _missionItemCount(%10) roiSupported(%11) orbitSupported(%12) _missionActive(%13) _hideROI(%14) _hideOrbit(%15)",
"battery %1 level low": "电池 %1 电量低",
"directly": "直接",
"errno %1": "错误号 %1",
"fence breached": "围栏被突破",
"is difficult. Point the vehicle North before using it.": "较困难。使用前将载具指向北方。",
"maximum altitude": "最大高度",
"minimum altitude": "最小高度",
"not battery": "非电池",
"null": "空",
"primary": "主链路",
"prior to firmware upgrade.": "在固件升级之前。",
"results in zero diagonal and off-diagonal elements, so is only ": "导致对角线和非对角线元素为零，因此仅",
"secondary": "备用链路",
"suitable for vehicles where the field is close to spherical. It is ": "适用于磁场接近球形的载具。",
"trirotor": "三旋翼",
"useful for large vehicles where moving the vehicle to calibrate it ": "适用于大型载具，移动载具进行校准",
}

tree = ET.parse(ts_path)
root = tree.getroot()

filled = 0
not_found_set = set()

for ctx in root:
    for msg in ctx.findall('message'):
        trans_elem = msg.find('translation')
        if trans_elem is None:
            continue
        if trans_elem.get('type') == 'unfinished':
            source = msg.find('source')
            if source is None:
                continue
            src_text = source.text if source.text else ''
            if src_text in T:
                trans_elem.text = T[src_text]
                if 'type' in trans_elem.attrib:
                    del trans_elem.attrib['type']
                filled += 1
            else:
                not_found_set.add(src_text[:60])

tree.write(ts_path, encoding='utf-8', xml_declaration=True)

print(f"Filled: {filled}")
print(f"Not found: {len(not_found_set)}")
if not_found_set:
    for s in sorted(not_found_set)[:10]:
        print(f"  MISSING: {repr(s)}")
