import xml.etree.ElementTree as ET
import re, html

ts_path = "translations/qgc_source_zh_CN.ts"

# 大型翻译映射表 - 英文源 -> 中文翻译
# 包含所有之前未匹配的复杂多行字符串
translations = {
"": "",
" (%1)": " (%1)",
" (Partial)": " (部分)",
" (Test Only)": " (仅测试)",
" ... ": " ... ",
" deg": " 度",
" disconnected ": " 未连接 ",
" doesn't take control in ": " 未接管 ",
" firmware upgrade.": " 固件升级。",
" is requesting control": " 正在请求控制",
"  Multiple buttons that have the same action must be pressed simultaneously to invoke the action.": "  具有相同动作的多个按钮必须同时按下才能执行该动作。",
"  seconds": "  秒",
"  seconds ...": "  秒...",
"  to a powered USB port on your computer, not through a USB hub. ": "  到电脑的带电 USB 端口，不要通过 USB 集线器。",
"  To change this configuration, select the desired frame class below and then reboot the vehicle.": "  要更改此配置，请在下方选择所需的机架类别，然后重启载具。",
"  via USB to ": "  通过 USB 连接到 ",
"%": "%",
"%1": "%1",
"%1 can upgrade the firmware on Pixhawk devices and SiK Radios.": "%1 可以升级 Pixhawk 设备和 SiK 电台的固件。",
"%1 Config": "%1 配置",
"%1 does not support loading this complex mission item type: %2:%3": "%1 不支持加载此复杂任务项类型：%2:%3",
"%1 Version": "%1 版本",
"%1Communication lost": "%1 通信丢失",
"%1Communication lost on %2 link.": "%1 通信在 %2 链路上丢失。",
"%1Communication regained": "%1 通信恢复",
"%1Communication regained on %2 link": "%1 通信在 %2 链路上恢复",
"%1Switching communication to new primary link": "%1 切换通信到新的主链路",
"%1Switching communication to secondary link.": "%1 切换通信到备用链路。",
"(AMSL)": "(AMSL)",
"(CalcT)": "(计算地形)",
"(Param not available)": "(参数不可用)",
"(Passed)": "(通过)",
"(TerrF)": "(地形)",
"* Avoid tailwind on approach to land.": "* 避免顺风进近降落。",
"* Ensure landing distance is enough to complete transition.": "* 确保降落距离足够完成转换。",
", ": "，",
"--.--": "--.--",
"/TAGGED": "/TAGGED",
"/TAGGED folder in your image folder": "/图片文件夹中的 TAGGED 文件夹",
"<default location>": "<默认位置>",
"<None>": "<无>",
"100Hz": "100Hz",
"10Hz": "10Hz",
"1Hz": "1Hz",
"25Hz": "25Hz",
"2Hz": "2Hz",
"30 ft": "30 英尺",
"3D Map File:": "3D 地图文件：",
"3D mode: Off": "3D 模式：关",
"3D mode: On": "3D 模式：开",
"3D View": "3D 视图",
"3DR Solo (requires restart)": "3DR Solo（需重启）",
"3Hz": "3Hz",
"4Hz": "4Hz",
"50Hz": "50Hz",
"5Hz": "5Hz",
"6Hz": "6Hz",
"7Hz": "7Hz",
"8Hz": "8Hz",
"9Hz": "9Hz",
"A higher value makes the vehicle react faster. Be aware that this affects braking as well, and a combination of slow responsiveness with high maximum velocity will lead to long braking distances.": "较高的值使载具反应更快。注意这也会影响制动，慢响应与高最大速度的组合会导致较长的制动距离。",
"Abort": "中止",
"Absolute pressure": "绝对压力",
"Accel 1: %1": "加速度计 1：%1",
"Accel 2: %1": "加速度计 2：%1",
"Accel 3: %1": "加速度计 3：%1",
"Accelerometer": "加速度计",
"Accelerometer 2": "加速度计 2",
"Accelerometer(s):": "加速度计：",
"Account": "账户",
"Accuracy": "精度",
"Accuracy (u-blox only)": "精度（仅 u-blox）",
"Acquire <br> Control": "获取<br>控制",
"Acres": "英亩",
"Acro": "特技",
"Actions": "动作",
"Actual AMSL alt sent: %1 %2": "实际发送的 AMSL 高度：%1 %2",
"Actual Rate:": "实际速率：",
"Actuator action command failed": "执行器动作命令失败",
"Actuator Outputs": "执行器输出",
"Actuator test command denied": "执行器测试命令被拒绝",
"Actuator test command failed": "执行器测试命令失败",
"Actuator test command not supported": "执行器测试命令不支持",
"Actuator test command temporarily rejected": "执行器测试命令被临时拒绝",
"Actuator Testing": "执行器测试",
"Actuators": "执行器",
"Add": "添加",
"Add New Link": "新增链路",
"Add New Set": "添加新地图块组",
"Add Server": "添加服务器",
"Additional errors received": "收到额外错误",
"Additional Feedback:": "额外反馈：",
"Address": "地址",
"Adquire Control": "获取控制",
"ADSB Server": "ADSB 服务器",
"Advanced Mode": "高级模式",
"Advanced Settings": "高级设置",
"AirLink": "AirLink",
"AirLink Link Settings": "AirLink 链路设置",
"Airship": "飞艇",
"Airship, controlled": "飞艇，有控",
"Airspeed": "空速",
"ALERT": "警报",
"All Altitudes": "所有高度",
"All Files (*)": "所有文件 (*)",
"All Motors": "所有电机",
"Allow configuring multiple landing sequences": "允许配置多个降落序列",
"Allow takeover": "允许接管",
"Alt (rel)": "高度（相对）",
"Altitude": "高度",
"Altitude & Airspeed": "高度和空速",
"Altitude Type": "高度类型",
"AMSL": "AMSL",
"Analyze Tools": "分析工具",
"Analyze vibration associated with your vehicle.": "分析与载具相关的振动。",
"Angular rate control": "角速率控制",
"AP Mode": "AP 模式",
"APM ArduCopter Vehicle": "APM ArduCopter 载具",
"APM ArduPlane Vehicle": "APM ArduPlane 载具",
"APM ArduRover Vehicle": "APM ArduRover 载具",
"APM ArduSub Vehicle": "APM ArduSub 载具",
"Append to existing sets": "追加到既存地图块组",
"Application Load/Save Path": "应用加载/保存路径",
"Application restart required after change": "更改后需要重启应用",
"Application Settings": "应用设置",
"Apply": "应用",
"Apply new altitude": "应用新高度",
"Apply Preset": "应用预设",
"Approach": "进近",
"ArduCopter": "ArduCopter",
"ArduPilot": "ArduPilot",
"ArduPilot Users Forum": "ArduPilot 用户讨论区",
"ArduPlane": "ArduPlane",
"Are you sure you want to cancel the upload?": "确认取消上传过程？",
"Arm": "解锁",
"Arm (MV)": "解锁（多载具）",
"Arm selected vehicles.": "解锁选中的载具。",
"ARM STATUS": "解锁状态",
"Arm Status Error": "解锁状态错误",
"Armed": "已解锁",
"Aspect Ratio": "宽高比",
"Attitude Controller": "姿态控制器",
"Attitude stabilization": "姿态稳定",
"Auto": "自动",
"Auto-Center Throttle": "推进杆自动回中",
"AutoConnect": "自动连接",
"Auto-Delete Saved Recordings": "自动删除已保存录像",
"Autoland": "自动降落",
"Automatic": "自动",
"Autopilot Orientation": "自驾仪朝向",
"Autotune": "自动调参",
"Autotune successful.": "自动调参成功。",
"Average Building Level Height": "平均建筑层高",
"Avoid ADSB": "避让 ADSB",
"Avoidance/collision prevention": "避障/防碰撞",
"Axis": "轴",
"Az: ": "方位角：",
"Backwards": "向后",
"Barometer(s):": "气压计：",
"BASIC ID": "基本 ID",
"Basic ID": "基本 ID",
"Battery": "电池",
"Battery ": "电池 ",
"Battery %1": "电池 %1",
"Battery Display": "电池显示",
"Battery: ": "电池：",
"Baud Rate": "波特率",
"Baudrate": "波特率",
"Beep": "蜂鸣",
"Bing Tile Above Zoom Level": "必应地图块超出缩放级别",
"Blend": "混合",
"Blend Opacity": "混合不透明度",
"Blue Robotics Power Sense Module": "Blue Robotics 电源检测模块",
"Bluetooth": "蓝牙",
"Bluetooth Devices": "蓝牙设备",
"boundary": "边界",
"Brand Image": "品牌图片",
"Breach action": "突破动作",
"Breach Action": "突破动作",
"Breeze": "微风",
"Broadcast": "广播",
"Broadcast Message": "广播消息",
"Browse": "浏览…",
"Button Assignment": "按钮分配",
"Buttons": "按钮",
"Calc Above Terrain": "按地形计算",
"Calculated Above Terrain": "按地形计算",
"Calculated Font Height: ": "计算得到的字体高度：",
"Calculated Screen Height: ": "计算得到的屏幕高度：",
"Calculated Screen Width: ": "计算得到的屏幕宽度：",
"Calibration failed: No matching triggers found for images.": "校准失败：未找到与图片匹配的触发。",
"Calibration failed: No triggers or images available.": "校准失败：无可用触发或图片。",
"Calm": "无风",
"Camera": "相机",
"Camera mount tilt speed:": "相机安装倾斜速度：",
"Camera Tracking": "相机追踪",
"Cancel": "取消",
"Cancel Download": "取消下载",
"Cancel ROI": "取消 ROI",
"Cancel Upload": "取消上传",
"Careful : Motors are enabled": "注意：电机已启用",
"Careful: Actuator sliders are enabled": "注意：执行器滑块已启用",
"Celsius": "摄氏度",
"Center": "居中",
"Change": "更改",
"Change Airspeed": "更改空速",
"Change Heading": "更改航向",
"Change Heading not supported by Vehicle.": "载具不支持更改航向。",
"Change Loiter Radius": "更改盘旋半径",
"Change Max Ground Speed": "更改最大地速",
"Channel 15": "通道 15",
"Channel 16": "通道 16",
"Channel Monitor": "通道监视器",
"Check All": "全选",
"Check None": "全不选",
"Choose custom brand image file": "选择自定义品牌图片文件",
"Choose the location to save/load files": "选择文件保存/加载位置",
"Circle": "绕圈",
"Circle centered on Home": "以起飞点为中心绕圈",
"Clear": "清除",
"Clear All": "全部清除",
"Clear all settings on next start": "下次启动时清除所有设置",
"Clear Emergency": "清除紧急状态",
"Click to refresh...": "点击刷新...",
"Clip count": "片段数",
"Close": "关闭",
"Close %1": "关闭 %1",
"Closing device failed": "关闭设备失败",
"Coaxial helicopter": "共轴直升机",
"Color Scheme": "配色方案",
"Coloring": "着色",
"Comm Links": "通信链路",
"Comm Lost": "通信丢失",
"Comms Lost": "通信丢失",
"Communication Links": "通信链路",
"Comp %1": "组件 %1",
"Comp All": "所有组件",
"Comp ID": "组件 ID",
"Compass Motor Interference Calibration": "罗盘电机干扰校准",
"Compasses:": "罗盘：",
"Component %1": "组件 %1",
"Conductivity: ": "电导率：",
"Configure": "配置",
"Confirm": "确认",
"Confirm canceling the upload process?": "确认取消上传过程？",
"Confirm Delete": "确认删除",
"Confirm deleting selected log files?": "确认删除所选日志文件？",
"Confirm erasing all files?": "确认擦除所有文件？",
"Confirm frame %1": "确认机架 %1",
"Confirm resetting all settings?": "确认重置所有设置？",
"Confirm uploading selected log files?": "确认上传所选日志文件？",
"Connect": "连接",
"Connect not allowed during Flight Data replay.": "飞行数据回放期间不允许连接。",
"Connected": "已连接",
"Connecting...": "连接中…",
"Connection": "连接",
"Connection failed": "连接失败",
"Connection Failed: %1": "连接失败：%1",
"Connection failed: %1": "连接失败：%1",
"Console": "控制台",
"Consumed": "已消耗",
"Control type: ": "控制类型：",
"Coordinate System": "坐标系",
"Course Over Ground": "航迹向",
"Crash (pilot error)": "严重故障（操作原因）",
"Crash (software/hardware failure)": "严重故障（软件/硬件原因）",
"Crashed (Pilot Error)": "坠毁（操作原因）",
"Crashed (Software or Hardware issue)": "坠毁（软件或硬件问题）",
"CrashLogs": "崩溃日志",
"Critical": "严重",
"Critical Level": "严重级别",
"CRSF Bind": "CRSF 对频",
"Cruise": "巡航",
"Current Accuracy": "当前精度",
"Custom": "自定义",
"Custom Map URL": "自定义地图 URL",
"Data Bits": "数据位",
"Data to Send is Empty": "待发送数据为空",
"Database Not Initialized": "数据库未初始化",
"Date": "日期",
"Date & Time": "日期和时间",
"dBm": "dBm",
"Debug": "调试",
"Debug Touch Areas": "调试触摸区域",
"Default": "默认",
"Default Description:": "默认描述：",
"Default font height:": "默认字体高度：",
"Default Font Height: ": "默认字体高度：",
"Default font pixel size:": "默认字体像素大小：",
"Default Font Pixel Size: ": "默认字体像素大小：",
"Default font point size:": "默认字体点大小：",
"Default Font Point Size: ": "默认字体点大小：",
"Default font width:": "默认字体宽度：",
"Default Font Width: ": "默认字体宽度：",
"Default Mission Altitude": "默认任务高度",
"Default Point Size: ": "默认点大小：",
"Default Point:": "默认点：",
"Default Upload URL": "默认上传地址",
"Default Upload URL:": "默认上传地址：",
"deg/s": "度/秒",
"Delete": "删除",
"Delete Link": "删除链路",
"Delete log file after upload": "上传后删除日志文件",
"Delete Log Files": "删除日志文件",
"Delete Preset": "删除预设",
"Delete Selected": "删除所选",
"Delete Selected Log Files": "删除所选日志文件",
"Depth Hold": "定深保持",
"Deselect All": "全部取消选择",
"Desktop Available Height:": "桌面可用高度：",
"Desktop Available Height: ": "桌面可用高度：",
"Desktop Available Width:": "桌面可用宽度：",
"Desktop Available Width: ": "桌面可用宽度：",
"Device": "设备",
"Disabled": "禁用",
"Disarm": "上锁",
"Disarm (MV)": "上锁（多载具）",
"Disarm selected vehicles.": "上锁选中的载具。",
"Discard Unsaved Changes": "放弃未保存的更改",
"Disconnect": "断开",
"Disconnected": "未连接",
"Disconnected - Click to manually connect": "未连接 - 点击手动连接",
"Dist prev WP:": "距上一航点：",
"Distance": "距离",
"Dock": "停靠",
"Done": "完成",
"Done fencing": "完成围栏",
"Don't have an account?": "没有账户？",
"Double-click to exit full screen": "双击退出全屏",
"Download": "下载",
"Download map tiles for use when offline": "下载地图块数据供离线时使用",
"Downloaded:": "已下载：",
"Downloading": "下载中",
"Downwards": "向下",
"Duration": "持续时间",
"Edit": "编辑",
"Edit Center Position": "编辑中心位置",
"Edit Displayed Flight Modes": "编辑显示的飞行模式",
"Edit Link": "编辑链路",
"Edit Parameter": "编辑参数",
"Edit Position": "编辑位置",
"Edit ROI Position": "编辑 ROI 位置",
"Edit Vertex Position": "编辑顶点位置",
"Either firmware list is still downloading, or no firmware is available for current selection.": "固件列表仍在下载中，或当前选择无可用固件。",
"Elevation Provider": "高程数据提供商",
"Email address for Log Upload:": "日志上传邮箱：",
"EMERGENCY": "紧急",
"Emergency Level": "紧急级别",
"Empty Filename.": "文件名为空。",
"Empty Plan": "空计划",
"Empty Reply": "空回复",
"Enable": "启用",
"Enable auto record (when vehicle is armed)": "启用自动记录（设备启用时）",
"Enable auto upload": "启用自动上传",
"Enable automatic log uploads": "启用自动日志上传",
"Enable automatic logging": "启用自动日志记录",
"Enable Multi-Vehicle Panel": "启用多载具面板",
"Enable NTRIP/RTK": "启用 NTRIP/RTK",
"Enabled": "已启用",
"End Time": "结束时间",
"Enforce Preflight Checklist": "强制执行检查清单",
"Enter Commands here...": "在此输入命令…",
"Enter name": "输入名称",
"Enter preset name": "输入预设名称",
"Error": "错误",
"Error Count:": "错误计数：",
"Error Message": "错误信息",
"Esri": "Esri",
"Est Size:": "预计大小：",
"EU Vehicle Info": "欧盟载具信息",
"Exit": "退出",
"Exit Plan": "退出计划",
"Export": "导出",
"Export Map Tiles": "导出地图块组",
"Export Selected Tile Sets": "导出所选地图块组",
"Export Tiles": "导出地图块",
"Exporting": "正在导出",
"Extended Status": "扩展状态",
"External ground truth": "外部真值",
"Extra 1": "附加 1",
"Extra 2": "附加 2",
"Extra 3": "附加 3",
"Factory reset": "恢复出厂设置",
"Fahrenheit": "华氏度",
"Failsafe Options": "故障保护选项",
"Fast Calibration": "快速校准",
"FBW A": "FBW A",
"FBW B": "FBW B",
"Feedback:": "补充说明：",
"Feet": "英尺",
"Firmware": "固件",
"Fixed Wing": "固定翼",
"Fixed wing aircraft": "固定翼飞行器",
"Fixed Wing Landing": "固定翼降落",
"Flapping wing": "扑翼",
"Flight Behavior": "飞行行为",
"Flight Modes": "飞行模式",
"Flight Rating:": "任务评价：",
"Flight Speed": "飞行速度",
"Fly": "飞行",
"Fly View": "飞行视图",
"Fly View Actions": "航行界面动作",
"Flying": "飞行中",
"Follow": "跟随",
"Follow Me": "跟随我",
"For Accelerometer calibration you will need to place your vehicle on all six sides on a perfectly level surface and hold it still in each orientation for a few seconds.": "加速度计校准需要将载具放在平整表面上六个面各静置几秒钟。",
"For Compass calibration you will need to rotate your vehicle through a number of positions.": "罗盘校准需要将载具旋转经过多个位置。",
"For Gyroscope calibration you will need to place your vehicle on a surface and leave it still.": "陀螺仪校准需要将载具放在表面上保持静止。",
"Force Arm": "强制解锁",
"Force Video Decoder": "强制视频解码器",
"Format": "格式",
"Frame selection": "机架选择",
"Free balloon, uncontrolled": "自由气球，无控",
"Free Space: ": "剩余空间：",
"Full": "满",
"Function": "功能",
"Gale": "大风",
"General": "通用",
"Generic": "通用",
"Generic Vehicle": "通用载具",
"GeoFence": "电子围栏",
"Geographic": "地理",
"Geometry": "几何",
"Gimbal ": "云台 ",
"Gimbal Yaw Follow": "云台偏航跟随",
"Gimbal Yaw Lock": "云台偏航锁定",
"Go to location": "前往位置",
"Go To Location Max Distance": "前往位置最大距离",
"Good": "良好",
"GPS": "GPS",
"GPS Lock": "GPS 锁定",
"Grams": "克",
"Great": "优秀",
"Gripper Close": "夹爪关闭",
"Gripper Function": "夹爪功能",
"Gripper Open": "夹爪打开",
"Ground Control Comm Loss Failsafe": "地面站通信丢失故障保护",
"Ground installation": "地面安装",
"Ground rover": "地面漫游车",
"Ground Station": "地面站",
"Ground Station Connection": "地面站连接",
"Ground Station Name": "地面站名称",
"Group": "组",
"GStreamer Debug Level": "GStreamer 调试级别",
"Guided": "引导",
"Guided Commands": "引导命令",
"Gyro": "陀螺仪",
"Gyro 2": "陀螺仪 2",
"HDOP": "HDOP",
"Hectares": "公顷",
"Height (rel)": "高度（相对）",
"Help": "帮助",
"Herelink AirUnit": "Herelink 空中端",
"Herelink Hotspot": "Herelink 热点",
"Hexarotor": "六旋翼",
"Hold": "保持",
"Horizontal": "水平",
"Horizontal Distance": "水平距离",
"Horizontal Distance: m": "水平距离：米（m）",
"Horizontal FOV": "水平视场角",
"Host Name / Address": "主机名 / 地址",
"Hz": "Hz",
"Identify & Assign Motors": "识别并分配电机",
"Ignore": "忽略",
"Image is Empty": "图片为空",
"Import": "导入",
"Import Map Tiles": "导入地图块",
"Import Tiles": "导入地图块",
"Import TileSets": "导入地图块组",
"Importing": "正在导入",
"In Progress": "进行中",
"In progress": "进行中",
"Inclusion/Exclusion Circles+Polygons": "包含/排除圆和多边形",
"Indoor Image": "室内图片",
"Info": "信息",
"Initial Waypoint Alt": "初始航点高度",
"Initializing": "初始化中",
"Insert Geofence": "插入电子围栏",
"Instrument Panel": "仪表",
"Invalid Baud Rate": "无效波特率",
"Invalid Cache Tile": "无效缓存图块",
"Invalid Directory.": "无效目录。",
"Invalid Filename.": "无效文件名。",
"Invalid Operator ID": "无效操作员 ID",
"Invalid Reply": "无效回复",
"Joystick Actions": "摇杆动作",
"Joystick buttons speed:": "摇杆按钮速度：",
"Keep Current Plan": "保留当前计划",
"Keep Map Centered On Vehicle": "地图始终跟随目标",
"Key": "密钥",
"Kilograms": "千克",
"KML Files (*.%1)": "KML 文件 (*.%1)",
"KML/SHP Files (*.%1 *.%2)": "KML/SHP 文件 (*.%1 *.%2)",
"Knots": "节",
"L": "左",
"Landing": "降落",
"Language: Chinese ": "语言：中文 ",
"Left-Handed Mode (swap sticks)": "左手模式（交换摇杆）",
"Leftwards": "向左",
"LibrePilot": "LibrePilot",
"Link Status (Current Vehicle)": "链路状态（当前载具）",
"Link Status (Current Vehicle))": "链路状态（当前载具）",
"Links": "链路",
"List of available devices": "可用设备列表",
"Load KML/SHP...": "加载 KML/SHP…",
"Load New Plan From Vehicle": "从载具加载新计划",
"Load Parameters": "加载参数",
"Local Video Storage": "本地视频存储",
"Lock Compass Nose-Up": "锁定指南针为船头向上",
"Log Download": "日志下载",
"Log File": "日志文件",
"Log Record": "日志记录",
"Logging": "日志",
"Login": "登录",
"Login:": "登录：",
"Logout": "退出登录",
"Loiter": "盘旋",
"Loiter Radius in Forward Flight Guided Mode": "前飞引导模式盘旋半径",
"Lon: %1": "经度：%1",
"Loss rate:": "丢包率：",
"Loss Rate:": "丢包率：",
"Loss Timeout": "丢包超时",
"Low": "低",
"Low Battery Failsafe": "低电量故障保护",
"Low Latency Mode": "低延迟模式",
"Magnetic Declination": "磁偏角",
"Magnetometer": "磁力计",
"Magnetometer 2": "磁力计 2",
"Manual": "手动",
"Manual Start/Stop:": "手动开始/停止：",
"Manually create connection after change": "变更后手动创建连接",
"Maps": "地图",
"Map Style": "地图样式",
"Mapbox": "Mapbox",
"Mapbox Login": "Mapbox 登录",
"Max Altitude": "最大高度",
"Max Climb Rate": "最大爬升率",
"Max Descent Rate": "最大下降率",
"Max Distance": "最大距离",
"Max speed:": "最大速度：",
"Max Storage Usage": "最大占用空间",
"Max Zoom: %1": "最大缩放：%1",
"Maximum Altitude": "最大高度",
"Meters": "米",
"Min Altitude": "最小高度",
"Min Duration": "最短持续时间",
"Min Zoom: %1": "最小缩放：%1",
"Min/Max Zoom Levels": "最小/最大缩放级别",
"Minimum Altitude": "最小高度",
"Mission Altitude": "任务高度",
"Mission Start": "任务开始",
"Mission Turning Radius": "任务转弯半径",
"Missions do not require takeoff item": "任务不需要起飞条目",
"Mock Link": "模拟链接",
"Motor Detection": "电机检测",
"Motor outputs / control": "电机输出/控制",
"Mountpoint": "挂载点",
"Move": "移动",
"MPEG-TS Video Stream": "MPEG-TS 视频流",
"Multi Vehicle Actions": "多载具动作",
"Multi Vehicle Selection": "多载具选择",
"Multirotor": "多旋翼",
"Multi-Rotor": "多旋翼",
"Mute all audio output": "静音（关闭所有音频输出）",
"N/A": "不可用",
"n/a": "不可用",
"Name": "名称",
"Network Not Available": "网络不可用",
"New User? Register Now": "新用户？立即注册",
"New Version Available": "有新版本可用",
"No": "否",
"No Boats": "无在线无人船",
"No error": "无错误",
"No firmware support": "无固件支持",
"No Links Configured": "未配置链路",
"No Messages": "无消息",
"No to All": "全部选否",
"No USVs online": "无在线无人船",
"No Video Available": "无可用视频",
"No wind": "无风",
"None Available": "无可用",
"Normal": "正常",
"Not Available": "不可用",
"Not Connected": "未连接",
"NOT CONNECTED": "未连接",
"Not Mapped": "未映射",
"Not Ready": "未就绪",
"Not Yet Valid": "尚未有效",
"Notice": "通知",
"NTRIP Manager not available": "NTRIP 管理器不可用",
"Octorotor": "八旋翼",
"Off": "关闭",
"Offline Maps": "离线地图",
"Ok": "确定",
"On": "开启",
"Open": "打开",
"OpenStreetMap files (*.osm)": "OpenStreetMap 文件 (*.osm)",
"Operator ID": "操作员 ID",
"Optical flow": "光流",
"Optical Flow": "光流",
"Option": "选项",
"Orientations": "朝向",
"Outdoor Image": "室外图片",
"Overall Status": "总状态",
"P: ": "俯仰：",
"Palette Test": "调色板测试",
"Parity": "校验",
"Parrot Discovery": "Parrot Discovery",
"Parse failed": "解析失败",
"Password": "密码",
"Password:": "密码：",
"Pause": "暂停",
"PH: ": "PH值：",
"Photo Interval (seconds)": "拍照间隔（秒）",
"Photo Mode": "拍照模式",
"Picture In Picture": "画中画",
"PID Tuning": "PID 调参",
"Pitch": "俯仰",
"Pixhawk": "Pixhawk",
"Plan View": "计划视图",
"Please configure ground station connection first": "请先配置地面站连接",
"Please fill in the email address before uploading the log.": "上传日志前请先填写邮箱地址。",
"Please select": "请选择",
"Please Select": "请选择",
"Please select an OSM file": "请选择 OSM 文件",
"Port": "端口",
"Position": "位置",
"Position Hold": "位置保持",
"Pounds": "磅",
"Powered by %1": "由 %1 驱动",
"Pre-Arm Check": "起飞前检查",
"Precision Landing": "精准降落",
"Pre-Flight Checklist": "出航前检查清单",
"Preset Name": "预设名称",
"Presets": "预设",
"Progress": "进度",
"Propulsion": "推进",
"Provider": "提供商",
"Provides a connection to the vehicle's system shell.": "提供到载具系统 shell 的连接。",
"Proximity": "接近",
"PX4 Log Transfer": "PX4 日志传输",
"PX4 Pro": "PX4 Pro",
"PX4 Users Forum": "PX4 用户讨论区",
"QGroundControl Discord Channel": "QGroundControl Discord 频道",
"QGroundControl User Guide": "QGroundControl 用户指南",
"Qt Platform:": "Qt 平台：",
"Qt Platform: ": "Qt 平台：",
"R": "集结点",
"Rate": "速率",
"Raw Sensors": "原始传感器",
"RC Channels": "RC 通道",
"Ready to calibrate.": "准备校准。",
"Ready To Fly": "准备起飞",
"Reboot the vehicle prior to flight.": "飞行前请重启载具。",
"Record File Format": "录制文件格式",
"Refresh": "刷新",
"Register": "注册",
"Relative To Launch": "相对于起飞点",
"Remaining": "剩余",
"Remaining Capacity:": "剩余容量：",
"Remote ID": "远程 ID",
"Remove vertex": "移除顶点",
"Replace existing sets": "替换既存地图块组",
"Reset": "重置",
"Reset Images": "重置图片",
"Retry": "重试",
"Return to Launch": "返回起飞点",
"Rocket": "火箭",
"ROI at location": "在位置处设置 ROI",
"Roll": "横滚",
"RTK": "RTK",
"RTK / NTRIP": "RTK 差分（NTRIP）",
"RTK GPS Settings": "RTK GPS 设置",
"RTK GPS Status": "RTK GPS 状态",
"RTL": "返航",
"RTL Altitude": "返航高度",
"RTSP URL": "RTSP 地址",
"RTSP Video Stream": "RTSP 视频流",
"Satellites": "卫星数",
"Save": "保存",
"Save All": "全部保存",
"Save App Log": "保存应用日志",
"Save CSV telemetry log": "保存遥测数据 CSV 日志",
"Save log after each flight": "每次任务结束后保存日志",
"Save logs even when vehicle is not armed": "即使载具未解锁也保存日志",
"Save Preset": "保存预设",
"Saved Log Files": "已保存的日志文件",
"Search": "搜索",
"Search:": "搜索：",
"sec": "秒",
"Select All": "全选",
"Select File": "选择文件",
"Select map file": "选择地图文件",
"Select None": "全不选",
"Select USV": "选择无人船",
"Self ID": "自身 ID",
"Send": "发送",
"Send Heartbeat": "发送心跳包",
"Send Request": "发送请求",
"Send status text + voice broadcast": "发送状态信息 + 语音播报",
"Send to Vehicle": "发送到载具",
"Sensor Status": "传感器状态",
"Serial Port": "串口",
"Server Address": "服务器地址",
"Server Port": "服务器端口",
"Server URL": "IP 地址",
"Set Estimator Origin": "设置估计器原点",
"Set Flight Mode": "设置飞行模式",
"Set Heading": "设置航向",
"Set Home": "设置起飞点",
"Settings": "设置",
"Show additional heading indicators on Compass": "指南针显示更多航向指示",
"Show Joystick Status in Toolbar": "工具栏显示摇杆状态",
"Show Telemetry Log Replay Status Bar": "显示遥测回放状态栏",
"SiK Radio": "SiK 电台",
"Simple": "简单",
"Single": "单个",
"Size 10": "字号 10",
"Size 10.5": "字号 10.5",
"Size 11": "字号 11",
"Size 11.5": "字号 11.5",
"Size 12": "字号 12",
"Size 12.5": "字号 12.5",
"Size 13": "字号 13",
"Size 13.5": "字号 13.5",
"Size 14": "字号 14",
"Size 14.5": "字号 14.5",
"Size 15": "字号 15",
"Size 15.5": "字号 15.5",
"Size 16": "字号 16",
"Size 16.5": "字号 16.5",
"Size 17": "字号 17",
"Size:": "大小：",
"Smart RTL": "智能返航",
"Source": "来源",
"Spacing": "间距",
"Speed": "速度",
"Speed Unit": "速度单位",
"Stabilize": "自稳",
"start": "开始",
"Start": "开始",
"Start Record": "开始记录",
"Start Time": "开始时间",
"Statistics": "统计",
"Status": "状态",
"Steering": "转向",
"Stop": "停止",
"Stop Bits": "停止位",
"Stop Record": "停止记录",
"Stop recording when disarmed": "未启用控制时停止录制",
"Storage": "存储",
"Storm": "暴风",
"Stream GCS Position": "发送地面站位置",
"Stream Rates (ArduPilot only)": "数据流频率（仅 ArduPilot）",
"Strong wind": "大风",
"Sub": "水下",
"Submarine": "潜水器",
"Surface": "水面",
"Survey-In": "测量定位",
"Syncing Mission": "同步任务中",
"System in control: ": "控制系统：",
"Takeoff": "起飞",
"Telemetry": "遥测",
"Temperature": "温度",
"Temperature: °C": "温度：摄氏度（°C）",
"Terrain": "地形",
"Time": "时间",
"Time Lapse": "延时摄影",
"TODO": "待办",
"Tokens": "令牌",
"Tolerance": "容差",
"Total Messages Lost": "丢包总数",
"Total Messages Received": "已接收消息总数",
"Total Messages Sent (estimated)": "已发送消息总数（估算）",
"Total:": "总计：",
"Training": "训练",
"Transition to Fixed Wing": "转换为固定翼",
"Transition to Multi-Rotor": "转换为多旋翼",
"Turbidity: ": "浊度：",
"Type": "类型",
"UDP": "UDP",
"UDP Port": "UDP 端口",
"UDP URL": "UDP 地址",
"UI Scaling": "界面缩放",
"Unknown": "未知",
"Unknown Format": "未知格式",
"Unknown sensor": "未知传感器",
"Unsatisfactory": "不满意",
"Update return to home position based on device location.": "根据设备位置更新返航点",
"Upload Email:": "上传邮箱：",
"Upload Log Files": "上传日志文件",
"Upload Selected": "上传所选",
"Uploaded": "已上传",
"Use Preflight Checklist": "启用出航前检查清单",
"Use SPARTN (not supported yet)": "使用 SPARTN（暂不支持）",
"Used to tag a set of images from a survey mission with gps coordinates. You must provide the binary log from the flight as well as the directory which contains the images to tag.": "用于将一组测量任务图片与 GPS 坐标关联。您需要提供飞行的二进制日志以及包含待标记图片的目录。",
"Username": "用户名",
"USV": "无人船",
"Value": "值",
"VDOP": "VDOP",
"Vehicle": "载具",
"Vehicle Configuration": "载具配置",
"Vehicle Messages": "载具消息",
"Vehicle Parameters": "载具参数",
"Vehicle Position": "载具位置",
"Vehicle Power": "载具电源",
"Vehicle Type": "载具类型",
"Vehicles Altitude Bias": "显示偏置",
"Vertical": "垂直",
"Vertical Distance": "垂直距离",
"Vertical Distance: m": "垂直距离：米（m）",
"Vertical FOV": "垂直视场角",
"Video": "视频",
"Video Source": "视频源",
"Video Stream": "视频流",
"Video URL:": "视频地址：",
"Virtual Joystick": "虚拟摇杆",
"Voltage:": "电压：",
"VTOL": "VTOL",
"VTOL Landing": "VTOL 降落",
"VTOL Tailsitter": "VTOL 尾座式",
"VTOL TransitionDistance": "VTOL 转换距离",
"W": "西",
"Wait for disarm": "等待上锁",
"Waiting for data...": "等待数据...",
"Waiting for parameters...": "等待参数...",
"Warning": "警告",
"warning": "警告",
"Warning Level": "警告级别",
"Water Quality": "水质",
"Water Temp: ": "水温：",
"Weight": "重量",
"Whitelist (IP/Device)": "白名单（IP/设备）",
"Wind & weather": "风力和天气",
"Wind Speed:": "风速：",
"Wind:": "风力：",
"Y: ": "偏航：",
"Yaw": "偏航",
"Yes": "是",
"Yes to All": "全部选是",
"Zoom": "缩放",
"Zoom Levels:": "缩放级别：",
}

# 用 ElementTree 解析 XML（支持复杂多行 source）
tree = ET.parse(ts_path)
root = tree.getroot()

filled = 0
not_found_set = set()

for ctx in root:
    for msg in ctx.findall('message'):
        trans_elem = msg.find('translation')
        if trans_elem is None:
            continue
        if trans_elem.get('type') == 'unfinished':
            source = msg.find('source')
            if source is None:
                continue
            src_text = source.text if source.text else ''
            if src_text in translations:
                trans_elem.text = translations[src_text]
                # 移除 type 属性标记为已完成
                del trans_elem.attrib['type']
                filled += 1
            else:
                not_found_set.add(src_text[:60])

# 保存
tree.write(ts_path, encoding='utf-8', xml_declaration=True)

print(f"Filled: {filled}")
print(f"Not found: {len(not_found_set)}")
if not_found_set:
    for s in sorted(not_found_set)[:15]:
        print(f"  MISSING: {repr(s)}")
